### ISSUE TITLE
公開範囲が「公開」なのは過剰ではないでしょうか

### ISSUE THREAD

**Issue by hidao80** [sanbongazin/TodoListDon-GUI#1]
公開範囲が「公開」（=Public）なのは、LTLのほかユーザの目にも触れ、個人的なリマインダとしては公開範囲が過剰だと考えます。  
LTLをメインに利用するユーザが存在する可能性が高いMastodonにおいては、公開範囲「公開」で個人的なリマインドをするのは公開範囲が適切でないと考えます。

### 代案

公開範囲を「非収載」（=Unlisted）または「非公開」（=Private）にしてはいかがでしょうか。  
それでも個人的な通知として利用する目的は達せられると思うのですが。

例）  
下記ソースのPostNewStatusにvisibilityパラメータをつけたほうが良いと考えますが、いかがでしょうか？

https://github.com/sanbongazin/TodoListDon-GUI/blob/233a3392945660819fe157f967dc06416fd8f612/MainWindow.cs#L166

```cs
client.PostNewStatus(status: TodoString +"#"+ UserName +"_On_TodoListDon", visibility: Enums.Visibility.Private);
```

**Comment by sanbongazin** [comment]
ありがとうございます。
人の目の監視がほしいという人もいるかなと思ったのですが、
そういった需要はなく、むしろセキュアな面が損なわれそうだということが
みうけられそうですので、デフォルトの公開範囲はそうしようかと思います。
早速、そのように反映いたします。

**Comment by hidao80** [comment]
@sanbongazin 
なるほど、人の目の監視があると「やならきゃ」感が強まりますね。とても効果的だと思います。
ですが、LTLはあくまで公の場ですので、人の目を気にするのなら非収載（=当該インスタンスのLTL以外で閲覧可能）か非公開（=フォロワーのみ）でも効果あるのではないでしょうか。

### 本Issueの意図の補足

本Issueではセキュアな面よりも、**本ツールを使用していない他の当該インスタンスユーザが「定期的にどうでもいい人のToDoが何度も差し込まれるのがじゃまくさい」と感じる面**を気にしています。

特に私がメインで利用しているQiitaodonというインスタンスでは、**LTLを大半のインスタンスユーザで共有し、HTLをあまり利用しない**という利用形態が多く見受けられ、その場合に本アプリのTootがものすごいノイズに感じられます（個人の感想です）。

表現がキツくなってしまって申し訳ありません。🙇‍♂️
対応を検討くださり、ありがとうございます。🙏

**Comment by sanbongazin** [comment]
＞本Issueの意図の補足について
確かにそうですね。相手側の立場からすれば、目障り以外の何物でもないでしょう。
そこら編の気遣いがなっていなかった点は、次回からのまた、これからのソフトの反省点だと言えます。AutoTooterなどが最も良い例だと考えられます。
マストドンは公共の場という点を見失わずに、できればと思います。
まだまだ未熟ですが、よろしくおねがいします。
